function Privacy() {
  return (
    <div className="min-h-screen bg-black text-white">
      {/* Background Effects */}
      <div className="fixed inset-0">
        <div className="absolute inset-0 bg-gradient-to-b from-deeper-blue/[0.02] to-transparent"></div>
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-deeper-blue/[0.02] rounded-full blur-3xl"></div>
      </div>

      <div className="relative">
        {/* Navigation */}
        <nav className="container mx-auto px-6 py-8">
          <a href="/" className="text-white text-2xl font-medium tracking-wider">
            DEEPER
          </a>
        </nav>

        {/* Privacy Content */}
        <main className="container mx-auto px-4 sm:px-6 pt-12 sm:pt-24 pb-20">
          <div className="max-w-3xl mx-auto">
            <div className="bg-white/[0.02] backdrop-blur-3xl rounded-2xl border border-white/[0.05] p-8 sm:p-12">
              <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>
              <p className="text-gray-400 mb-8">Last updated: January 31, 2025</p>

              <div className="space-y-8 text-gray-400">
                <p>
                  This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </p>
                
                <p>
                  We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                </p>

                <h2 className="text-2xl font-semibold text-deeper-blue mt-12 mb-6">Interpretation and Definitions</h2>
                
                <h3 className="text-xl font-semibold text-white mb-4">Interpretation</h3>
                <p>
                  The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>

                <h3 className="text-xl font-semibold text-white mb-4">Definitions</h3>
                <p>For the purposes of this Privacy Policy:</p>
                <ul className="list-disc pl-6 space-y-4">
                  <li><strong className="text-white">Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                  <li><strong className="text-white">Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                  <li><strong className="text-white">Application</strong> refers to Deeper, the software program provided by the Company.</li>
                  <li><strong className="text-white">Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Deeper.</li>
                  <li><strong className="text-white">Country</strong> refers to: Serbia</li>
                  <li><strong className="text-white">Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                  <li><strong className="text-white">Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                  <li><strong className="text-white">Service</strong> refers to the Application.</li>
                  <li><strong className="text-white">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                  <li><strong className="text-white">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                  <li><strong className="text-white">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>

                <h2 className="text-2xl font-semibold text-deeper-blue mt-12 mb-6">Contact Us</h2>
                <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>By email: <a href="mailto:adrian@deepersoftware.com" className="text-deeper-blue hover:text-blue-400 transition-colors">adrian@deepersoftware.com</a></li>
                  <li>By visiting this page on our website: <a href="https://www.deepersoftware.com/support" className="text-deeper-blue hover:text-blue-400 transition-colors">https://www.deepersoftware.com/support</a></li>
                </ul>
              </div>
            </div>
          </div>
        </main>

        {/* Footer */}
        <footer className="container mx-auto px-4 sm:px-6 py-8 border-t border-white/[0.05]">
          <div className="flex justify-center">
            <div className="text-sm text-gray-500 font-light">
              © 2025 Deeper - Work with Depth
            </div>
          </div>
        </footer>
      </div>
    </div>
  )
}

export default Privacy 